strapi/client

- README.md
- src/index.ts
- src/sdk.ts
- tests/unit/index.test.ts
**Description:**
- Renamed `createStrapiSDK` function to `strapiSDK`.
- Fixed formatting in README code example (that were considered errors).
Align with other SDK conventions
N/A
> chore: rename sdk constructor

- .github/ISSUE_TEMPLATE/BUG_REPORT.yml
**Description:**
Improved the bug report by adding more inputs and rewording others
> chore(repository): enhance bug report template

- .github/ISSUE_TEMPLATE/BUG_REPORT.yml
Use text area inputs instead of markdown, since the later can't accept user input
Fix the bug report template.
> fix(repository): update bug report template formatting

- README.md
- rollup.config.mjs
- Updated the documentation for debugging techniques and SDK usage.
- Documentation needed enhancements to provide clearer guidance for debugging and SDK utilization.
- Refer to the updated documentation section on debugging and SDK usage.
> doc: debug

- README.md
- pnpm-lock.yaml
Add a link to the roadmap in the repo readme
Help users understand what's planned for the future
> docs(README): add link to SDK roadmap in resources

- README.md
- pnpm-lock.yaml
- src/auth/factory/factory.ts
- src/auth/manager.ts
- src/auth/providers/abstract.ts
- src/auth/providers/api-token.ts
- src/auth/providers/users-permissions.ts
- src/content-types/collection/manager.ts
- src/content-types/single/manager.ts
- src/errors/index.ts
- src/errors/strapi.ts
- src/http/client.ts
- src/index.ts
- src/sdk.ts
- src/utilities/url-helper.ts
- src/validators/index.ts
- src/validators/sdk.ts
- src/validators/url.ts
- tests/unit/auth/factory.test.ts
- tests/unit/auth/providers/api-token.test.ts
- tests/unit/auth/providers/users-permissions.test.ts
- tests/unit/errors/sdk-errors.test.ts
- tests/unit/index.test.ts
- tests/unit/mocks/index.ts
- tests/unit/mocks/sdk-validator.mock.ts
- tests/unit/mocks/strapi-config-validator.mock.ts
- tests/unit/sdk.test.ts
- tests/unit/validators/strapi-config.test.ts
Rename instances of `StrapiSDK` by `Strapi` and `strapiSDK` by `strapi`.
Update in code, tests, documentation and comments.
Adopt a more conventional a developer-friendly naming for the SDK constructor.
The tests should work as usual, it's advised to manually test the built library with an example
> enhancement: rename the SDK constructor

- src/types/content-api.ts
Adds `string[]` type to populate types.
String arrays is already supported by the populate attributes, but the typings just didn't support it yet.
Should build als usual, a missing type has been added to support already existing functionality.
https://github.com/strapi/sdk-js/issues/26
Previous pull request #28 which I messed up.
> fix: add string array to populate types

- src/interceptors/http.ts
- tests/unit/interceptors/http.test.ts
- tests/unit/sdk.test.ts
Make sure the `setDefaultHeaders` HTTP interceptor doesn't override manually set headers.
see https://github.com/strapi/sdk-js/issues/27
Using `sdk.fetch` with a custom content type header should not override said header with `application/json`
Alternatively, running the unit tests ensures the behavior is correct based on `tests/unit/sdk.test.ts` and `tests/unit/sdk.test.ts`
fix #27
> fix(interceptors): prevent overriding existing headers

- README.md
- src/index.ts
- src/sdk.ts
- tests/unit/index.test.ts
- tests/unit/sdk.test.ts
Simplifies the auth configuration by flattening the properties.
Basically
```typescript
strapi({
baseURL: '...',
auth: {
strategy: 'api-token',
options: {
token: '<token>'
}
}
})
```
becomes
```typescript
strapi({
baseURL: '...',
auth: '<token>'
})
``` 
Improve the developer experience when using the SDK
See example above, it should work the same for the undocumented `users-permission` provider
> feat(auth): refactor auth configuration logic

- README.md
udpates readme with demo script changes
updated
> chore: update readme for demo

- .commitlintrc.ts
Adds a rule to allow commit messages starting with "Update" or "Merge" without errors.
To prevent commitlint errors for common GitHub commit messages.
Commit with "Update" or "Merge" messages and check for no errors.
N/A
> chore: ignore github messages in commitlint

- src/index.ts
Add four new types and interfaces to the public SDK surface:
- `Strapi` represents the sdk instance API
- `StrapiConfig` is the configuration object that is used to configure the strapi instance
- `CollectionTypeManager` is the object returned by a call to `client.collection('<ct>')`
- `SingleTypeManager` is the object returned by a call to `client.single('<st>')`
Allow users to reference common sdk objects in their code without having to infer them from values
- Build the bundles & setup the demos
- Head to the TS demo
- You should be able to import the types and use them as expected. You should not be able to use them as values.
resolves https://github.com/strapi/sdk-js/issues/33
> enhancement(sdk): extend the public type api

- src/content-types/collection/manager.ts
- src/content-types/single/manager.ts
- tests/unit/content-types/collection/collection-manager.test.ts
- tests/unit/content-types/collection/single-manager.test.ts
`create` and `update` need to be sent as `application/json` instead of `text/plain`
they were failing if they weren't sent explicitly
run update and create with the sdk and they should work
Let us know if this is related to any issue/pull request
> fix: send content-type as application/json when necessary

- .github/ISSUE_TEMPLATE/BUG_REPORT.yml
- README.md
- demo/node-javascript/package.json
- demo/node-javascript/pnpm-lock.yaml
- demo/node-javascript/src/index.js
- demo/node-typescript/package.json
- demo/node-typescript/pnpm-lock.yaml
- demo/node-typescript/src/index.ts
- package.json
- rollup.config.mjs
- src/auth/manager.ts
- src/auth/providers/users-permissions.ts
- src/client.ts
- src/errors/strapi.ts
- src/http/client.ts
- src/index.ts
- src/validators/client.ts
- src/validators/index.ts
- tests/unit/client.test.ts
- tests/unit/errors/client-errors.test.ts
- tests/unit/index.test.ts
- tests/unit/validators/strapi-config.test.ts
Renames the project and all references to it from `sdk-js` to `client`
`sdk-js` was redundant and unclear what the project was about
Everything should work as before, except with the new package name
Let us know if this is related to any issue/pull request
> chore: rename sdk-js to client

- README.md
- demo/.strapi-app/config/admin.ts
- there is no `sdk:http` so I replaced with the correct`strapi:http`
-  do not autoopen demo admin
Describe the issue you are solving.
Provide information about the environment and the path to verify the behaviour.
Let us know if this is related to any issue/pull request
> chore: fix debug string and do not autoopen demo admin

- .prettierignore
- CONTRIBUTING.md
- README.md
- package.json
Add a `CONTRIBUTING.md` documentation file to the repository root.
Details the following points:
- 📋 Prerequisites
- 🛠 Setting Up the Project
- 1. Clone the Repository
- 2. Install Dependencies
- 🏗️ Compiling the Changes
- Build
- Watch
- Output
- 🧪 Testing the Changes
- Unit Tests
- Running Unit Tests
- Test Coverage
- Configuration
- Writing Tests
- Mocks
- Demos
- Setting Up the Demos
- Run the Demos
- 🔎 Verifying Your Contribution
- 📝 Commit Messages
- 🎉 You're Ready to Contribute!
- 🔐 Pull Request Reviews
- The Review
- Merging a PR
- 📚 Releases
Better document the contribution process, remove friction for both first time contributors and maintainers
> docs: add contribution documentation 

- README.md
- demo/node-javascript/src/index.js
- demo/node-typescript/src/index.ts
- src/files/constants.ts
- src/files/manager.ts
- src/files/types.ts
- tests/unit/files/files-client-integration.test.ts
- tests/unit/files/files-manager.test.ts
Adds file metadata update capabilities to the existing `FilesManager` class:
1. New method in the `FilesManager` class:
- `update(id, data)`: Updates file metadata for a specific file by ID
2. Enhanced type definitions:
- `FileUpdateData` interface for metadata update parameters
- `FileUpdateResponse` type for the update operation result
4. Error handling for common update scenarios:
- Non-existent file
- Invalid update data format
The current implementation only allows retrieving files. This addition enables modifying file metadata in the Strapi Media Library.
1. Testing file metadata updates:
```typescript
// Update multiple attributes at once
const updatedFile = await client.files.update(12, {
name: "banner-image",
alternativeText: "Company banner",
caption: "For homepage header"
}); …
```
> Update file metadata

- package.json
- rollup.config.mjs
- src/client.ts
- src/exports.ts
- src/index.ts
- src/validators/client.ts
- tests/fixtures/http-error-associations.ts
- tests/unit/auth/factory.test.ts
- tests/unit/auth/providers/api-token.test.ts
- tests/unit/auth/providers/users-permissions.test.ts
- tests/unit/client.test.ts
- tests/unit/errors/client-errors.test.ts
- tests/unit/errors/http-errors.test.ts
- tests/unit/files/files-client-integration.test.ts
- tests/unit/index.test.ts
- tests/unit/interceptors/auth.test.ts
- tests/unit/validators/strapi-config.test.ts
- Renamed `Strapi` to `StrapiClient` to better understand its purpose
- Renamed `StrapiConfig` to `StrapiClientConfig` to follow the associated class' change
- Moved the client's `files` accessor from a getter to a property by making it public and renaming it from `_files` to `files`
- Added backward compatibility by keeping aliases of previously exported types, added todo to make sure they get removed in v2
Cleanup, improve developer experience.
Everything should work just like previous versions, new types should be available
> enhancement(client): rename Strapi to StrapiClient 

- package.json
- rollup.config.mjs
Force to only resolve browser-compatible modules at build time, for both browser and node builds
Fix issues encountered when using the client with client-side framework like react or angular.
fix #69 
fix #62 
fix #61 (to be tested)
> fix(build): force browser-compatible module resolution in builds

- src/client.ts
- src/index.ts
- src/validators/client.ts
- tests/unit/validators/strapi-config.test.ts
Now we can add some custom headers for all request to strapi client.
Can be useful when needed to ask for only draft or preview mode
I added unit test related to it, and config for headers was already here just not consume
Issue : [#77](https://github.com/strapi/client/issues/77)
> feat: :sparkles: add the option to pass custom headers

- README.md
Covers the changes made in https://github.com/strapi/client/pull/76 in the repo README
> docs(readme): add section for configuring custom headers in Strapi client

- README.md
- demo/react-vite/package.json
- demo/react-vite/pnpm-lock.yaml
- demo/react-vite/src/app.tsx
- demo/react-vite/src/hooks/useFiles.ts
- demo/react-vite/src/pages/CollectionDemo.tsx
- src/client.ts
- src/content-types/abstract.ts
- src/content-types/collection/manager.ts
- src/content-types/single/manager.ts
- tests/unit/client.test.ts
- tests/unit/content-types/collection/collection-manager.test.ts
- tests/unit/content-types/collection/single-manager.test.ts
> Original idea by @alexandrebodin in https://github.com/strapi/client/issues/24#issuecomment-2666008740
Introduce a new feature that allows users to customize the path for the content-type managers' instance.
It aims to provide greater flexibility in how queries are made against Strapi app, especially those having heavy customization (or simply want to use the CT managers for plugins' models)
- Developers can now specify custom paths for content types managers from the client's calls
- `strapi.collection('foo', { path: '/plugin/baz/foo' });`
- `strapi.single('bar', { path: '/my-custom-path' });`
- Unit tests added for new path configuration functionality
- Manual testing performed across the different demos
Documentation has been updated to include:
- Configuration guide for custom paths …
> feat(content-types): allow custom root paths for CT managers

- demo/node-typescript/src/index.ts
- src/client.ts
- src/content-types/abstract.ts
- src/content-types/collection/manager.ts
- tests/unit/content-types/collection/collection-manager.test.ts
Adds plugin-specific handling to the Strapi client library. The changes include:
- Added optional `plugin` configuration parameter to `ContentTypeManagerOptions` with configurable name and prefix
- Implemented conditional data wrapping logic that skips wrapping payloads for the users-permissions plugin
- Enhanced route construction to support plugin-specific prefixes (e.g., `/plugin-name/resource` or `/resource` for plugins without prefixes)
- Updated the client's `collection()` method to accept plugin configuration options
The users-permissions plugin in Strapi has a different API contract than regular content-types. It expects raw payload data without the standard `{ data: {...} }` wrapper that other content-types require. Without this change, attempting to create users via the client …
> Plugin specific support (users-permissions)
